### ISSUE TITLE
Err was: name 'socket' is not defined

### ISSUE THREAD

**Issue by izevar** [rai68/gpsd-easy#1]
Hello I was trying to make your plugin working but looks like python do not want to cooperate :)

21:08:36 [INFO] [gpsdeasy] plugin loading begin
21:08:37 [INFO] [gpsdeasy] GPSd is installed, continuing
21:08:37 [INFO] [gpsdeasy] Updating autoconfig if changed
21:08:37 [INFO] [gpsdeasy] finished updating configs, Updated: True
21:08:38 [INFO] [gpsdeasy] Connecting to gpsd socket at 127.0.0.1:2947
21:08:38 [WARNING] [gpseasy] error occured during socket setup, try power cycle the device. Err was: name 'socket' is not defined

probably it's something around line 55.

**Comment by rai68** [comment]
use https://github.com/jayofelony/pwnagotchi-torch-plugins/blob/main/gpsdeasy.py

the one here is in development
