### ISSUE TITLE
Apt Update

### ISSUE THREAD

**Issue by renewedbullet** [rai68/gpsd-easy#2]
add apt update to pull gpsd info from repo's,this can cause issues with initial install if the user hasnt already done an apt update it will say installing, installed and never actually install.

I believe the bottom code should be able to do a apt update on initial setup then do the install.

if 'installed' not in aptRes.stdout:
    logging.info('[gpsdeasy] GPSd not installed, trying now. This may take up to 5 minutes just let me run')
    if is_connected():
        subprocess.run(['apt', 'update'])
        subprocess.run(['apt', 'install', '-y', 'gpsd', 'gpsd-clients'])

**Comment by rai68** [comment]
fixed in past updates
