### ISSUE TITLE
The baud rate is not getting picked up properly on my "M100" 115200 baud gps

### ISSUE THREAD

**Issue by Sniffleupagus** [rai68/gpsd-easy#4]
I have noticed a lot of the time on that the gps led is blinking, but gpsdeasy is showing no data. I tried using gpsmon and cgps to view it, and it isn't receiving data. If I shutdown gpsd and "screen /dev/ttyS1 115200" it dumps gps data every time. gpsd only comes up correctly a small fraction of the time.

I just changed the code that creates /etc/default/gpsd to add "-s {self.baud}" to the GPSD_OPTIONS, like (around line 189):

`        baseConf = [
            f'GPSD_OPTIONS="-n -N -b -s {self.baud}"\n', 
            f'BAUDRATE="{self.baud}"\n',
            f'MAIN_GPS="{self.device}"\n',
            f'PPS_DEVICES="{self.pps_device}"\n',
            'GPSD_SOCKET="/var/run/gpsd.sock"\n',
            '/bin/stty -F ${MAIN_GPS} ${BAUDRATE}\n',
            '/bin/setserial ${MAIN_GPS} low_latency\n'
        ]
`
and it seems to fix it.  gpsd is coming up right every time. If I take the "-s" clause out, it fails again.  put it back and it succeeds over and over.

Maybe it could be optional, and only add that if "baud" is in options.

**Comment by rai68** [comment]
Im confused, why not just put baud in config?

**Comment by Sniffleupagus** [comment]
Because it wasn't working.

Without it, gpsd tries to figure it out, and was getting it wrong most of the time. Adding it to the command line options makes it work every time.

**Comment by rai68** [comment]
the baud is added to the command line

**Comment by Sniffleupagus** [comment]
I'm not sure what you mean. Did you add it to the command line somewhere?

**Comment by rai68** [comment]
huh not sure how i missed that, the whole time, i just made an edit wanna give it a go? just config device and baud
